core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('user/', include('user.urls')),
    path('produk/', include('produk.urls')),
    path('laporan/', include('laporan.urls')),
    path('transaksi/', include('transaksi.urls')),
]

home/urls.py
from django.urls import path
from .views import index

app_name = 'app'

urlpatterns = [
    path('', index, name='home')
]

laporan/urls.py
from django.urls import path
from .views import laporan

app_name = 'laporan'

urlpatterns = [
    path('', laporan, name='home'),
]

produk/urls.py
from django.urls import path
from .views import produk

app_name = 'produk'

urlpatterns = [
    path('', produk, name='home'),
]

transaksi/urls.py
from django.urls import path
from .views import transaksi

app_name = 'transaksi'

urlpatterns = [
    path('', transaksi, name='home'),
]

user/urls.py
from django.urls import path
from .views import auth_login

app_name = 'user'

urlpatterns = [
    path('login/', auth_login, name='login'),
]

home/models.py
from django.db import models

# Create your models here.

laporan/models.py
from django.db import models

# Create your models here.

produk/models.py
from django.db import models

# Create your models here.

transaksi/models.py
from django.db import models

# Create your models here.

user/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render, redirect, HttpResponse

def index(request):
    return render(request, 'index.html')

laporan/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.db import connection

def laporan(request):
    asd = ''
    with connection.cursor() as anggota:
        anggota.execute("SELECT * FROM anggota")
        asd = anggota.fetchall()
    return render(request, 'laporan.html', {'asd' : asd})

produk/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.db import connection

def produk(request):
    asd = ''
    with connection.cursor() as anggota:
        anggota.execute("SELECT * FROM produk")
        asd = anggota.fetchall()
    return render(request, 'produk.html', {'asd' : asd})

transaksi/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.db import connection

def transaksi(request):
    asd = ''
    with connection.cursor() as anggota:
        # ini contoh utk mau nge postgre
        anggota.execute("SELECT * FROM transaksi_baca")
        asd = anggota.fetchall()
        
    return render(request, 'transaksi.html', {'asd' : asd})

user/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.db import connection
from hashlib import sha3_512 as sha

def auth_login(request):
    asd = ''
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        hashed = sha(password.encode()).hexdigest()
        print(hashed)
    with connection.cursor() as anggota:
        anggota.execute("SELECT * FROM anggota")
        asd = anggota.fetchall()
    return render(request, 'login.html', {'asd' : asd})

home/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>hello</title>
{% endblock %}

{% block content %}
<!-- write code here -->
{% endblock %}

{% block script %}
{% endblock %}

laporan/templates/laporan.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>hello</title>
{% endblock %}

{% block content %}
<!-- write code here -->
{% for peep in asd %}

no_anggota {{ peep.0 }}
<br>
id {{ peep.1 }}
<br>
nama {{ peep.2 }}
<br>
alamat {{ peep.3 }}
<br>
tanggal_lahir {{ peep.4 }}
<br>
no_hp {{ peep.5 }}
<br>
ang_pembaca {{ peep.6 }}
<br>
ang_peminjam {{ peep.7 }}
<br>
<br>
<br>
{% endfor %}
{% endblock %}

{% block script %}
{% endblock %}

produk/templates/produk.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>hello</title>
{% endblock %}

{% block content %}
<!-- write code here -->
{% for peep in asd %}

    id {{ peep.1 }}
    <br>
    nama {{ peep.0 }}
    <br>
    jumlah {{ peep.2 }}
    <br>
    tipe_produk {{ peep.3 }}
    <br>
    <br>
    <br>

{% endfor %}
{% endblock %}

{% block script %}
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block head %}
    <title>hello</title>
    {% endblock %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'app:home' %}">
            {% if user.is_authenticated %}
                Hi {{ user.username }}
            {% else %}
                Hi Guest
            {% endif %}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="#">asd<span class="sr-only">(current)</span></a>
            </li>
            </ul>
    
            <ul class="navbar-nav my-2 my-lg-0">
                {% if user.is_authenticated %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'user:logout' %}">logout<span class="sr-only">(current)</span></a>
                    </li>
                {% else %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'user:login' %}">login<span class="sr-only">(current)</span></a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    {% block content %}{% endblock %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% block script %}{% endblock %}
</body>
</html>

transaksi/templates/transaksi.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>hello</title>
{% endblock %}

{% block content %}
<!-- write code here -->
{% for peep in asd %}

timestamp {{ peep.0 }}
<br>
jumlah_komik {{ peep.1 }}
<br>
jumlah_menu {{ peep.2 }}
<br>
total_biaya {{ peep.3 }}
<br>
no_anggota {{ peep.4 }}
<br>
kode {{ peep.5 }}
<br>
<br>
<br>
{% endfor %}
{% endblock %}

{% block script %}
{% endblock %}

user/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>login</title>
{% endblock %}

{% block content %}
<div class="container">
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {% if error %}
            <strong>{{ error }}</strong>
        {% endif %}
        <div class="form-group">
            <label for="usernameinput">Username</label>
            <input name="username" maxlength="50" type="text" class="form-control" id="usernameinput" placeholder="Enter username" required>
        </div>
        <div class="form-group">
            <label for="passwordinput">Password</label>
            <input name="password" type="password" class="form-control" id="passwordinput" placeholder="************" required>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

{% block script %}
{% endblock %}